# Generated by Django 6.0.6 on 2026-07-10 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('date', models.DateField(verbose_name='Дата')),
                ('location', models.CharField(max_length=100, verbose_name='Место')),
                ('status', models.CharField(choices=[('upcoming', 'предстоящее'), ('past', 'прошедшее')], default='upcoming', max_length=20)),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('cover_image', models.ImageField(upload_to='events/covers', verbose_name='Обложка')),
                ('registration_url', models.URLField(blank=True, verbose_name='Ссылка на регистрацию')),
                ('results_url', models.URLField(blank=True, verbose_name='Ссылка на результаты')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Distance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('length_km', models.DecimalField(decimal_places=2, max_digits=5)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('route_map_image', models.ImageField(blank=True, upload_to='events/routes', verbose_name='Схема трассы')),
                ('gpx_file', models.FileField(blank=True, upload_to='events/gpx', verbose_name='GPX трек')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distances', to='events.event')),
            ],
        ),
        migrations.CreateModel(
            name='BibPickupInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name='Инфо о выдаче номеров')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bib_pickup', to='events.event')),
            ],
            options={
                'verbose_name': 'Выдача номеров',
                'verbose_name_plural': 'Выдача номеров',
            },
        ),
        migrations.CreateModel(
            name='ScheduleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(verbose_name='Время')),
                ('title', models.CharField(max_length=200, verbose_name='Событие в программе')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_items', to='events.event')),
            ],
            options={
                'verbose_name': 'Пункт программы',
                'verbose_name_plural': 'Программа',
            },
        ),
        migrations.CreateModel(
            name='VenueInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=300, verbose_name='Адрес')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Долгота')),
                ('directions_text', models.TextField(blank=True, verbose_name='Как добраться')),
                ('parking_info', models.TextField(blank=True, verbose_name='Парковка')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='venue', to='events.event')),
            ],
            options={
                'verbose_name': 'Инфо о месте старта',
                'verbose_name_plural': 'Инфо о месте старта',
            },
        ),
        migrations.CreateModel(
            name='DistanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('male', 'мужчины'), ('female', 'женщины')], max_length=10, verbose_name='Категория')),
                ('athlete', models.CharField(max_length=100, verbose_name='Имя спортсмена')),
                ('result_time', models.DurationField(verbose_name='Результат')),
                ('date', models.DateField(verbose_name='Дата')),
                ('photo', models.ImageField(blank=True, upload_to='events/records', verbose_name='Фото')),
                ('distance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='events.distance')),
            ],
            options={
                'verbose_name': 'Рекорд дистанции',
                'verbose_name_plural': 'Рекорды дистанции',
                'unique_together': {('distance', 'gender')},
            },
        ),
    ]
