# Generated by Django 6.0.6 on 2026-07-10 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['home_order']},
        ),
        migrations.AddField(
            model_name='event',
            name='home_banner',
            field=models.ImageField(blank=True, upload_to='events/banners/', verbose_name='Баннер на главной'),
        ),
        migrations.AddField(
            model_name='event',
            name='home_order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Порядок на главной'),
        ),
        migrations.AlterField(
            model_name='distance',
            name='route_map_image',
            field=models.ImageField(blank=True, upload_to='events/routes/', verbose_name='Схема трассы'),
        ),
        migrations.AlterField(
            model_name='distancerecord',
            name='photo',
            field=models.ImageField(blank=True, upload_to='events/records/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='event',
            name='cover_image',
            field=models.ImageField(upload_to='events/covers/', verbose_name='Обложка'),
        ),
    ]
