# Generated by Django 6.0.6 on 2026-07-11 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_options_event_home_banner_and_more'),
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['home_order', 'date']},
        ),
        migrations.AddField(
            model_name='event',
            name='partners',
            field=models.ManyToManyField(blank=True, related_name='events', to='partners.partner', verbose_name='Партнёры'),
        ),
    ]
