# Generated by Django 6.0.6 on 2026-07-12 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_options_event_partners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='event',
            name='home_banner',
            field=models.ImageField(blank=True, help_text='~2000×700 px, формат JPG/WebP', upload_to='events/banners/', verbose_name='Баннер на главной'),
        ),
    ]
