# Generated by Django 6.0.6 on 2026-07-15 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_date_alter_event_home_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='venueinfo',
            name='start_map_image',
            field=models.ImageField(blank=True, help_text='~480px по ширине, JPG/PNG', upload_to='events/routes/', verbose_name='Схема трассы'),
        ),
        migrations.AlterField(
            model_name='distance',
            name='route_map_image',
            field=models.ImageField(blank=True, help_text='~600px по ширине, JPG/PNG', upload_to='events/routes/', verbose_name='Схема трассы'),
        ),
        migrations.AlterField(
            model_name='distancerecord',
            name='photo',
            field=models.ImageField(blank=True, help_text='~400px по ширине, 3/4, JPG/PNG', upload_to='events/records/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='event',
            name='cover_image',
            field=models.ImageField(help_text='~1000px по ширине, квадрат или 4/5, JPG/PNG', upload_to='events/covers/', verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='event',
            name='home_banner',
            field=models.ImageField(blank=True, help_text='~1900×500px, оставь место по краям, JPG/PNG', upload_to='events/banners/', verbose_name='Баннер на главной'),
        ),
    ]
