# Generated by Django 6.0.6 on 2026-07-17 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_venueinfo_start_map_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_recurring',
            field=models.BooleanField(default=False, verbose_name='Периодическое событие'),
        ),
        migrations.AddField(
            model_name='event',
            name='recurrence_text',
            field=models.CharField(blank=True, help_text='Если пусто — сформируется автоматически, например "Каждую субботу". Заполни вручную для нестандартных случаев ("Каждую 1-ю субботу месяца").', max_length=100, verbose_name='Текст расписания (переопределение)'),
        ),
        migrations.AddField(
            model_name='event',
            name='recurrence_weekday',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')], null=True, verbose_name='День недели'),
        ),
        migrations.AlterField(
            model_name='venueinfo',
            name='start_map_image',
            field=models.ImageField(blank=True, help_text='~480px по ширине, JPG/PNG', upload_to='events/routes/', verbose_name='Схема стартового городка'),
        ),
    ]
