# Generated by Django 6.0.6 on 2026-07-18 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_is_recurring_event_recurrence_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='home_banner',
            field=models.ImageField(blank=True, help_text='~1900×300px, оставь место по краям, JPG/PNG', upload_to='events/banners/', verbose_name='Баннер на главной'),
        ),
    ]
