# Generated by Django 6.0.6 on 2026-07-20 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_event_home_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='bottom_image',
            field=models.ImageField(blank=True, help_text='~400px по ширине, PNG с прозрачным фоном', upload_to='events/covers/', verbose_name='Картинка внизу страницы'),
        ),
    ]
