# Generated by Django 6.0.6 on 2026-07-21 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_event_waitlist_enabled_waitlistentry'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='waitlistentry',
            constraint=models.UniqueConstraint(fields=('event', 'email'), name='unique_waitlist_entry'),
        ),
    ]
