# Generated by Django 6.0.6 on 2026-07-26 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_waitlistentry_unique_waitlist_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='regulations_url',
            field=models.URLField(blank=True, verbose_name='Ссылка на положение'),
        ),
        migrations.AlterField(
            model_name='event',
            name='cover_image',
            field=models.ImageField(help_text='~1000px width, квадрат или 5/4, JPG/PNG', upload_to='events/covers/', verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='event',
            name='home_banner',
            field=models.ImageField(blank=True, help_text='~1000px width, 3/1, 30% картинки слева закроет плашка с текстом, JPG/PNG', upload_to='events/banners/', verbose_name='Баннер на главной'),
        ),
    ]
