# Generated by Django 6.0.6 on 2026-07-17 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Почта зачинщиков')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('tg_url', models.URLField(blank=True, verbose_name='Telegram')),
                ('vk_url', models.URLField(blank=True, verbose_name='VK')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
    ]
