# Generated by Django 6.0.6 on 2026-07-18 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Контакты зачинщиков', 'verbose_name_plural': 'Контакты зачинщиков'},
        ),
    ]
