# Generated by Django 6.0.6 on 2026-07-18 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0007_alter_event_home_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('photo', 'Фото'), ('video', 'Видео')], max_length=10, verbose_name='Тип')),
                ('image', models.ImageField(blank=True, help_text='Обязательно для типа "Фото"', upload_to='gallery/photo/', verbose_name='Фото')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Подпись')),
                ('video_embed_url', models.URLField(blank=True, help_text='Для типа "Видео". Например, embed-ссылка с vkvideo.ru или youTube', verbose_name='Ссылка для встраивания видео')),
                ('order', models.SmallIntegerField(default=0, verbose_name='Порядок')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_items', to='events.event')),
            ],
            options={
                'verbose_name': 'Медиафайл',
                'verbose_name_plural': 'Галерея',
                'ordering': ['order'],
            },
        ),
    ]
